BarayeAzadi/Controllers/ContactusController.cs
using BarayeAzadi.Application.Common.Utility;
using BarayeAzadi.Application.Services.Implementation;
using BarayeAzadi.Application.Services.Interface;
using BarayeAzadi.Domain.Entities;
using BarayeAzadi.Infrastructure.Migrations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BarayeAzadi.Web.Controllers
{
    public class ContactusController : Controller
    {
        private readonly IContactusService _contactusService;

        public ContactusController(IContactusService contactusService)
        {
            _contactusService = contactusService;
        }
        
        [Authorize(Roles =SD.Role_Admin)]
        public IActionResult Index()
        {
            return View(_contactusService.GetAllContactuss());   
        }
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult Details(int contactusId)
        {
            Contactus? obj = _contactusService.GetContactusById(contactusId);
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(obj);
        }
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult Delete(int contactId)
        {
            Contactus? obj =  _contactusService.GetContactusById(contactId);
            
            
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }
            bool deleted = _contactusService.DeleteContactus(obj);
            if (deleted)
            {
                TempData["success"] = "Statement has been deleted successfully!";
                return RedirectToAction(nameof(Index));

            }
            TempData["error"] = "Statement could not be deleted!";
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult Create(Contactus contactus)
        {
            if (contactus.Name.ToLower().ToString() == contactus.Message.ToLower().ToString())
            {
                ModelState.AddModelError("Name", "Message and Name could not be the same!");
            }
            if (ModelState.IsValid)
            {
                _contactusService.CreateContactus(contactus);

                TempData["success"] = "Your message has been sent successfully!";
                return RedirectToAction(nameof(Index), "Home");
            }
            TempData["error"] = "Message could not be created!Try again later!";
            
            return RedirectToAction(nameof(Create));
        }

    }
}

BarayeAzadi/Controllers/HomeEnglishController.cs
using BarayeAzadi.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BarayeAzadi.Controllers
{
    public class HomeEnglishController : Controller
    {
        private readonly ILogger<HomeEnglishController> _logger;

        public HomeEnglishController(ILogger<HomeEnglishController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CharterText()
        {
            return View();
        }
        public IActionResult Statements()
        {
            return View();
        }

        public IActionResult Contactus()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BarayeAzadi/Controllers/StatementController.cs
using BarayeAzadi.Application.Common.Utility;
using BarayeAzadi.Application.Services.Implementation;
using BarayeAzadi.Application.Services.Interface;
using BarayeAzadi.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BarayeAzadi.Web.Controllers
{
    public class StatementController : Controller
    {
        private readonly IStatementService _statementService;
        public StatementController(IStatementService statementService)
        {
            _statementService = statementService;
        }
        public IActionResult IndexFarsi()
        {
            return View(_statementService.GetAllStatement().Where(u => u.Language == "Farsi" && u.Type != "DemoVideo")
                .OrderByDescending(u => u.Created_Date));
        }
        public IActionResult IndexEnglish()
        {
            return View(_statementService.GetAllStatement().Where(u => u.Language == "English" && u.Type != "DemoVideo")
                .OrderByDescending(u => u.Created_Date));
        }
        public IActionResult DemoVideoEnglish()
        {
            return View(_statementService.GetAllStatement().Where(u => u.Language == "English" && u.Type=="DemoVideo")
                .OrderByDescending(u => u.StatementId));
                
        }
        public IActionResult DemoVideoFarsi()
        {
            return View(_statementService.GetAllStatement().Where(u => u.Language == "Farsi" && u.Type == "DemoVideo")
                .OrderByDescending(u => u.StatementId));

        }
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult IndexAdmin()
        {
            return View(_statementService.GetAllStatement());
        }
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = SD.Role_Admin)]
        [HttpPost]
        public IActionResult Create(Statement statement)
        {
            //if (!string.IsNullOrEmpty(statement.Text) && !string.IsNullOrEmpty(statement.MediaUrl))
            //{
            //    ModelState.AddModelError("Name", "Text and Media could not be empty at the same time!");
            //}
            if (ModelState.IsValid)
            {
                _statementService.CreateStatement(statement);

                TempData["success"] = "Your statement has been sent successfully!";
                return RedirectToAction(nameof(Index), "Home");
            }
            TempData["error"] = "Statement could not be created!Try again later!";

            return RedirectToAction(nameof(Create));
        }
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult Update(int statementId)
        {
            Statement? obj = _statementService.GetStatementById(statementId);
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(obj);
        }
        [Authorize(Roles = SD.Role_Admin)]
        [HttpPost]
        public IActionResult Update(Statement obj)
        {

            if (ModelState.IsValid && obj.StatementId > 0)
            {
                _statementService.UpdateStatement(obj);
                TempData["success"] = "Statement has been updated successfully!";
                return RedirectToAction(nameof(IndexAdmin));
            }
            TempData["error"] = "Statement could not be updated!";
            return View();
        }
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult Delete(int statementId)
        {
            Statement? obj = _statementService.GetStatementById(statementId);
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(obj);
        }
        [Authorize(Roles = SD.Role_Admin)]
        [HttpPost]
        public IActionResult Delete(Statement obj)
        {
            bool deleted = _statementService.DeleteStatement(obj.StatementId);
            if (deleted)
            {
                    TempData["success"] = "Statement has been deleted successfully!";
                    return RedirectToAction(nameof(IndexAdmin));

            }
            TempData["error"] = "Statement could not be deleted!";
            return View();
        }
        public IActionResult StatementText(int statementId)
        {
            Statement? obj = _statementService.GetStatementById(statementId);
            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(obj);
        }
    }
}

BarayeAzadi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa"  data-bs-theme="dark">
<head>

    <meta charset="utf-8" />
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-VTH37RXXVT"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-VTH37RXXVT');
    </script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>
        Baraye Azadi Group | گروه برای آزادی
    </title>
    <meta name="description" content="گروه برای آزادی شاهزاده رضا پهلوی را رهبر انقلاب ملی ایران و تنها راه برای سرنگونی جهموری اسلامی می داند  . زن زندگی آزادی مرد میهن آبادی" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css"
          integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/Spinner.css" />
    <link href="//cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" rel="stylesheet">

    
</head>
<body >

    <header>
        
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow ">
            
            <div class="container-fluid ">

                <a class="navbar-brand pull-right order-sm-last ms-2" asp-area="">
                    <img src="~/Static_Files/Images/logo.png" alt="logo" style="width:100px;" />
                </a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                     <ul class="navbar-nav  flex-nowrap">
                        

                        <partial name="_LoginPartial" />
                     </ul>
                    <ul class="navbar-nav ms-auto flex-nowrap">

                        <!--
                        <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Contactus" asp-action="Create">ارتباط با ما</a>
                        </li>
                        -->
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Statement" asp-action="DemoVideoFarsi">تجمعات</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Statement" asp-action="IndexFarsi">بیانیه ها</a>
                        </li>

                        <li class="nav-item ">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">صفحه اصلی</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Manager
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="dropdown-item">
                                        <a class="nav-link " asp-area="" asp-controller="Contactus" asp-action="Index">Messages</a>
                                    </li>
                                    <li class="dropdown-item">
                                        <a class="nav-link " asp-area="" asp-controller="Statement" asp-action="IndexAdmin">Statements</a>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                    
                </div>
                <a class="nav-link " asp-area="" asp-controller="HomeEnglish" asp-action="Index">
                    English
                    <img src="~/Static_Files/Images/lang-en.png" style="width:25px; height:17px; " />
                </a>
            </div>
        </nav>
        
        
    </header>

        <div class="container">
            <main role="main" class="pb-3">
                <partial name="_Notification" />
                @RenderBody()
                <br />
            <div class="sharethis-inline-share-buttons"></div>
            </main>
        </div>


    <footer class="border-top footer bg-dark text-muted mt-5">
        <div class="container text-center mb-3 flex-nowrap">
            Copyright © 2024 Baraye Azadi Group - All Rights Reserved.
            <br /><br />
            رسانه های اجتماعی ما
        </div>
        <div class="d-flex justify-content-center">
            <div class="me-4">
                <a href="https://www.instagram.com/baraye_azadi_group_austria">
                    <img src="~/Static_Files/Images/Instagram_icon.png" style="height:50px;" alt="Instagram" />
                </a>
            </div>
            <div class="ms-4 me-4">
                <a href="https://t.me/baraye_azadi_group">
                    <img src="~/Static_Files/Images/Telegram_icon.png" style="height:50px;" alt="Telgram" />
                </a>
            </div>
            <div class="ms-4 me-4">
                <a href="mailto:baraye.azadi.group@gmail.com">
                    <img src="~/Static_Files/Images/gmail_icon.png" style="height:50px;" alt="Gmail" />
                </a>
            </div>
            <div class="ms-4">
                <a href="https://twitter.com/barayazadigroup">
                    <img src="~/Static_Files/Images/x_icon.png" style="height:50px;" alt="X" />
                </a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.0.0/js/dataTables.min.js" asp-append-version="true"></script>
    <script src="~/js/jquery.unobtrusive-ajax.min.js"> </script>
    @await RenderSectionAsync("Scripts", required: false)

    <script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=663b82ae13418b001c9ca03b&product=inline-share-buttons&source=platform" async="async"></script>


</body>
</html>

BarayeAzadi/Views/Shared/_Layout_English.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Baraye Azadi Group | گروه برای آزادی</title>
    <meta name="description" content="The Baraye Azadi Group considers Prince Reza Pahlavi as the leader of the Iraniains National Revolution . Woman Life Freedom" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css"
          integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/Spinner.css" />
    <link href="//cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow">
            <div class="container-fluid">

                <a class="navbar-brand" asp-area="" >
                    <img src="~/Static_Files/Images/logo.png" alt="logo" style="width:100px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav  flex-nowrap">
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Manager
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="dropdown-item">
                                        <a class="nav-link " asp-area="" asp-controller="Contactus" asp-action="Index">Messages</a>
                                    </li>
                                    <li class="dropdown-item">
                                        <a class="nav-link " asp-area="" asp-controller="Statement" asp-action="IndexAdmin">Statements</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="HomeEnglish" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Statement" asp-action="DemoVideoEnglish">Demonstrations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Statement" asp-action="IndexEnglish">Statements</a>
                        </li>
                        <!--
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Contactus" asp-action="Create">Contactus</a>
                        </li>
                        -->
                    </ul>
                    
                    <ul class="navbar-nav ms-auto flex-nowrap">
                        <partial name="_LoginPartial" />
                        <li class="nav-item ">
                            <div class="d-flex  justify-content-center align-items-center">
                            </div>
                        </li>
                    </ul>
                    
                </div>
                <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Static_Files/Images/lang-fa.png" style="width:30px; height:17px" />
                    فارسی
                </a>
            </div>
        </nav>
    </header>

        <div class="container">
            <main role="main" class="pb-3">
                <partial name="_Notification" />
                @RenderBody()
            <br />
            <div class="sharethis-inline-share-buttons"></div>
            </main>
        </div>
   

    <footer class="border-top footer bg-dark text-muted mt-5">
        <div class="container text-center mb-3 flex-nowrap">
            Copyright © 2024 Baraye Azadi Group - All Rights Reserved.
            <br /><br />
            Our Social Medias
        </div>
        <div class="d-flex justify-content-center">
            <div class="me-4">
                <a href="https://www.instagram.com/baraye_azadi_group_austria">
                    <img src="~/Static_Files/Images/Instagram_icon.png" style="height:50px;" alt="Instagram" />
                </a>
            </div>
            <div class="ms-4 me-4">
                <a href="https://t.me/baraye_azadi_group">
                    <img src="~/Static_Files/Images/Telegram_icon.png" style="height:50px;" alt="Telgram" />
                </a>
            </div>
            <div class="ms-4 me-4">
                <a href="mailto:baraye.azadi.group@gmail.com">
                    <img src="~/Static_Files/Images/gmail_icon.png" style="height:50px;" alt="Gmail" />
                </a>
            </div>
            <div class="ms-4">
                <a href="https://twitter.com/barayazadigroup">
                    <img src="~/Static_Files/Images/x_icon.png" style="height:50px;" alt="X" />
                </a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.0.0/js/dataTables.min.js" asp-append-version="true"></script>
    <script src="~/js/jquery.unobtrusive-ajax.min.js"> </script>

    @await RenderSectionAsync("Scripts", required: false)

    <script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=663b82ae13418b001c9ca03b&product=inline-share-buttons&source=platform" async="async"></script>
</body>
</html>

BarayeAzadi/Views/Shared/_Layout_Farsi.cshtml
<!DOCTYPE html>
<html lang="fa"  data-bs-theme="dark">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>
        @ViewData["Title"] - گروه برای آزادی (وین - اتریش)
    </title>
    <meta name="description" content="گروه برای آزادی شاهزاده رضا پهلوی را رهبر انقلاب ملی ایران و تنها راه برای سرنگونی جهموری اسلامی می داند." />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css"
          integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/Spinner.css" />
    <link href="//cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" rel="stylesheet">
    
</head>
<body >
    <header>
        
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow ">
            
            <div class="container-fluid ">

                <a class="navbar-brand pull-right order-sm-last ms-2" asp-area="">
                    <img src="~/Static_Files/Images/logo.png" alt="logo" style="width:100px;" />
                </a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                     <ul class="navbar-nav  flex-nowrap">
                        

                        <partial name="_LoginPartial_Farsi" />
                     </ul>
                    <ul class="navbar-nav ms-auto flex-nowrap">


                        <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Contactus" asp-action="Create">ارتباط با ما</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Statement" asp-action="DemoVideoFarsi">تجمعات</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Statement" asp-action="IndexFarsi">بیانیه ها</a>
                        </li>

                        <li class="nav-item ">
                            <a class="nav-link " asp-area="" asp-controller="HomeFarsi" asp-action="Index">صفحه اصلی</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Manager
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="dropdown-item">
                                        <a class="nav-link " asp-area="" asp-controller="Contactus" asp-action="Index">Messages</a>
                                    </li>
                                    <li class="dropdown-item">
                                        <a class="nav-link " asp-area="" asp-controller="Statement" asp-action="IndexAdmin">Statements</a>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                    
                </div>
                <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">
                    English
                    <img src="~/Static_Files/Images/lang-en.png" style="width:25px; height:17px; " />
                </a>


            </div>
        </nav>
        
        
    </header>

        <div class="container">
            <main role="main" class="pb-3">
                <partial name="_Notification" />
                @RenderBody()
            </main>
        </div>


    <footer class="border-top footer bg-dark text-muted mt-5">
        <div class="container text-center mb-3 flex-nowrap">
            Copyright © 2024 Baraye Azadi Group - All Rights Reserved.
        </div>
        <div class="d-flex justify-content-center">
            <div class="me-5">
                <a href="https://www.instagram.com/baraye_azadi_group_austria">
                    <img src="~/Static_Files/Images/Instagram_icon.png" style="height:50px;" alt="Instagram" />
                </a>
            </div>
            <div class="ms-5 me-5">
                <a href="https://t.me/baraye_azadi_group">
                    <img src="~/Static_Files/Images/Telegram_icon.png" style="height:50px;" alt="Telgram" />
                </a>
            </div>
            <div class="ms-5">
                <a href="mailto:baraye.azadi.group@gmail.com">
                    <img src="~/Static_Files/Images/gmail_icon.png" style="height:50px;" alt="Telgram" />
                </a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.0.0/js/dataTables.min.js" asp-append-version="true"></script>
    <script src="~/js/jquery.unobtrusive-ajax.min.js"> </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BarayeAzadi/Views/Shared/_LoginPartial_English.cshtml
@using Microsoft.AspNetCore.Identity

@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager

@{
    ViewData["NoContainer"] = null;
}

<ul class="navbar-nav">

    @if (SignInManager.IsSignedIn(User))
    {
       
        <li class="nav-item">
            <a class="nav-link" href="#">Hello, @UserManager.GetUserName(User)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
        </li>
    }

</ul>

BarayeAzadi/Views/Shared/_LoginPartial_Farsi.cshtml
@using Microsoft.AspNetCore.Identity

@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager
@{
    ViewData["NoContainer"] = null;
}

<ul class="navbar-nav">

    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Hello, @UserManager.GetUserName(User)</a>
        </li>

    }
    else
    {
        <li class="nav-item">
            <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
        </li>

    }

</ul>